#!/bin/bash

docker run --rm --network="host"  --cap-add=ALL  --security-opt seccomp=unconfined -p 4222:4222 --ipc=host --memory 10G --memory-swap=10G --memory-swappiness=0  -v /dev/shm:/dev/shm -it loamobn/csbk bash  
