#!/bin/bash

docker run --rm --network="host"  --cap-add=ALL  --security-opt seccomp=unconfined -p 4222:4222 --ipc=host --memory 10G --memory-swap=10G --memory-swappiness=0  -v /dev/shm:/dev/shm -it loamobn/oprabk 


{
  "id": "/oprabk",
  "acceptedResourceRoles": [
    "slave_public"
  ],
  "backoffFactor": 1.15,
  "backoffSeconds": 1,
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ],
    [
      "hostname",
      "UNLIKE",
      "172.20.168.71"
    ]
  ],
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "loamobn/oprabk:latest",
      "forcePullImage": true,
      "privileged": true,
      "parameters": [
        {
          "key": "network",
          "value": "host"
        },
        {
          "key": "cap-add",
          "value": "ALL"
        },
        {
          "key": "ipc",
          "value": "host"
        },
        {
          "key": "security-opt",
          "value": "seccomp=unconfined"
        }
      ]
    }
  },
  "cpus": 8,
  "disk": 1024,
  "instances": 0,
  "maxLaunchDelaySeconds": 60,
  "mem": 4096,
  "gpus": 0,
  "networks": [
    {
      "mode": "host"
    }
  ],
  "portDefinitions": [
    {
      "name": "natsboard",
      "protocol": "tcp",
      "port": 3000
    },
    {
      "name": "secudb",
      "protocol": "tcp",
      "port": 23000
    }
  ],
  "requirePorts": true,
  "upgradeStrategy": {
    "maximumOverCapacity": 1,
    "minimumHealthCapacity": 1
  },
  "killSelection": "YOUNGEST_FIRST",
  "unreachableStrategy": {
    "inactiveAfterSeconds": 0,
    "expungeAfterSeconds": 0
  },
  "healthChecks": [],
  "fetch": []
}