#!/bin/bash
#

appname=OpraBook
app=oprabkapp
#args="-protobin -smbinsz 32 -bksnap 14:55 -avgbbosz 60 -avgsprd 60 -trdbk trdbk_opra -rbmpstrm rbmpstrm_opra -mpsprdmax 0.25 -mpscanamt 0.02 -opnint opnintbk -secudb optdb -bk oprabk -trdstrm trdstrm_opra -qstrm qstrm_opra -fdiface 10.254.32.81 -feed 233.43.202.[1-24]:[11101-11124]"

args="-config /scalp/RBConfig.json"


#export LD_PRELOAD=libonload.so
#export EF_POLL_USEC=100000
#export EF_RXQ_SIZE=4096
#export EF_MAX_PACKETS=524288
#export EF_STACK_PER_THREAD=1
#export EF_UDP_RCVBUF=16777216

. /scalp/script/startup $1
