#!/bin/bash
#

appname=OpraBkSnap
app=pubsubapp
args="13001 qstrm_opra -iface 172.20.168.70 -qbk oprabk -secudb optdb -snaponly -obfulldisc"

export LD_PRELOAD=libonload.so
export EF_POLL_USEC=100000
export EF_RXQ_SIZE=4096
export EF_MAX_PACKETS=524288
export EF_UDP_RCVBUF=8388608
export EF_NAME=opra

. /home/scalp/script/startup $1
