#!/bin/bash
#

appname=OpraBook
app=oprabkapp
args="-protobin -smbinsz 32 -bksnap 14:55 -avgbbosz 60 -avgsprd 60 -trdbk trdbk_opra -rbmpstrm rbmpstrm_opra -mpsprdmax 0.25 -mpscanamt 0.02 -opnint opnintbk -secudb optdb -bk oprabk -trdstrm trdstrm_opra -qstrm qstrm_opra -fdiface 10.254.32.78 -feed 233.43.202.[1-24]:[11101-11124]"

. /home/scalp/script/startup $1

#./$app $args
