#!/bin/bash
#

appname=quoteprotostream
app=streaminterfaceapp
args="qstrm_opra -qbk oprabk  -writeToMessageBroker -natsURL nats://localhost:4222"

#export LD_PRELOAD=libonload.so
#export EF_POLL_USEC=100000
#export EF_RXQ_SIZE=4096
#export EF_MAX_PACKETS=524288
#export EF_UDP_RCVBUF=8388608
#export EF_NAME=opra

. /home/scalp/script/startup $1
