// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mktdata.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mktdatamessage {

  /// <summary>Holder for reflection information generated from mktdata.proto</summary>
  public static partial class MktdataReflection {

    #region Descriptor
    /// <summary>File descriptor for mktdata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MktdataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1ta3RkYXRhLnByb3RvEg5ta3RkYXRhbWVzc2FnZSKQAgoKSW5zdHJ1bWVu",
            "dBI8Cg5JbnN0cnVtZW50VHlwZRgBIAEoDjIkLm1rdGRhdGFtZXNzYWdlLklu",
            "c3RydW1lbnQuSW5zdHJUeXBlEhgKEFVuZGVybHlpbmdTeW1ib2wYAiABKAkS",
            "FQoNRXhwaXJhdGlvbkRheRgDIAEoBRIXCg9FeHBpcmF0aW9uTW9udGgYBCAB",
            "KAUSFgoORXhwaXJhdGlvblllYXIYBSABKAUSDgoGU3RyaWtlGAYgASgCEhQK",
            "DElzQ2FsbE9wdGlvbhgHIAEoCBILCgNpZHgYCCABKA0iLwoJSW5zdHJUeXBl",
            "EgoKBkVRVUlUWRAAEgoKBk9QVElPThABEgoKBkZVVFVSRRACIpoDCgxUcmFk",
            "ZU1lc3NhZ2USEQoJVGltZXN0YW1wGAEgASgEEi8KC0luc3RydW1lbnRzGAIg",
            "AygLMhoubWt0ZGF0YW1lc3NhZ2UuSW5zdHJ1bWVudBINCgVQcmljZRgDIAEo",
            "AhIMCgRTaXplGAQgASgNEhQKDEV4Y2hhbmdlTmFtZRgFIAEoCRITCgtCaWRQ",
            "cmljZUJCTxgGIAEoAhITCgtBc2tQcmljZUJCTxgHIAEoAhISCgpCaWRTaXpl",
            "QkJPGAggASgNEhIKCkFza1NpemVCQk8YCSABKA0SFgoOQmlkRXhjaGFuZ2VC",
            "Qk8YCiABKAkSFgoOQXNrRXhjaGFuZ2VCQk8YCyABKAkSGAoQRGF5c0hpZ2hl",
            "c3RQcmljZRgMIAEoAhIXCg9EYXlzTG93ZXN0UHJpY2UYDSABKAISGAoQRGF5",
            "c09wZW5pbmdQcmljZRgOIAEoAhIXCg9EYXlzVG90YWxWb2x1bWUYDyABKA0S",
            "FAoMRXhjaGFuZ2VDb2RlGBAgASgNEhUKDUNvbmRpdGlvbkNvZGUYESABKA0i",
            "RQoQTWFya2V0RGVwdGhMZXZlbBINCgVQcmljZRgBIAEoAhIMCgRTaXplGAIg",
            "ASgNEhQKDEV4Y2hhbmdlQ29kZRgDIAEoDSKGAQoLUXVvdGVVcGRhdGUSEQoJ",
            "VGltZXN0YW1wGAEgASgEEi8KC0luc3RydW1lbnRzGAIgAygLMhoubWt0ZGF0",
            "YW1lc3NhZ2UuSW5zdHJ1bWVudBIzCglUb3BPZkJvb2sYAyABKAsyIC5ta3Rk",
            "YXRhbWVzc2FnZS5NYXJrZXREZXB0aExldmVsIosCChBCb29rRGVwdGhNZXNz",
            "YWdlEhEKCVRpbWVzdGFtcBgBIAEoBBIvCgtJbnN0cnVtZW50cxgCIAMoCzIa",
            "Lm1rdGRhdGFtZXNzYWdlLkluc3RydW1lbnQSNwoNQmlkQm9va0xldmVscxgD",
            "IAMoCzIgLm1rdGRhdGFtZXNzYWdlLk1hcmtldERlcHRoTGV2ZWwSNwoNQXNr",
            "Qm9va0xldmVscxgEIAMoCzIgLm1rdGRhdGFtZXNzYWdlLk1hcmtldERlcHRo",
            "TGV2ZWwSFAoMTnVtQmlkTGV2ZWxzGAUgASgNEhQKDE51bUFza0xldmVscxgG",
            "IAEoDRIVCg1Db25kaXRpb25Db2RlGAcgASgNImIKElF1b3RlTWVzc2FnZXNC",
            "YXRjaBIYChBOdW1iZXJPZk1lc3NhZ2VzGAEgASgNEjIKDVF1b3RlTWVzc2Fn",
            "ZXMYAiADKAsyGy5ta3RkYXRhbWVzc2FnZS5RdW90ZVVwZGF0ZSJjChJUcmFk",
            "ZU1lc3NhZ2VzQmF0Y2gSGAoQTnVtYmVyT2ZNZXNzYWdlcxgBIAEoDRIzCg1U",
            "cmFkZU1lc3NhZ2VzGAIgAygLMhwubWt0ZGF0YW1lc3NhZ2UuVHJhZGVNZXNz",
            "YWdlImcKEkRlcHRoTWVzc2FnZXNCYXRjaBIYChBOdW1iZXJPZk1lc3NhZ2Vz",
            "GAEgASgNEjcKDURlcHRoTWVzc2FnZXMYAiADKAsyIC5ta3RkYXRhbWVzc2Fn",
            "ZS5Cb29rRGVwdGhNZXNzYWdlInAKCURlYnVnSW5mbxIfChdNZXNzYWdlQ3Jl",
            "YXRlZFRpbWVzdGFtcBgBIAEoBBIcChRNZXNzYWdlU2VudFRpbWVzdGFtcBgC",
            "IAEoBBIVCg1NZXNzYWdlTnVtYmVyGAMgASgEEg0KBU90aGVyGAQgASgJQgJI",
            "AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mktdatamessage.Instrument), global::Mktdatamessage.Instrument.Parser, new[]{ "InstrumentType", "UnderlyingSymbol", "ExpirationDay", "ExpirationMonth", "ExpirationYear", "Strike", "IsCallOption", "Idx" }, null, new[]{ typeof(global::Mktdatamessage.Instrument.Types.InstrType) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mktdatamessage.TradeMessage), global::Mktdatamessage.TradeMessage.Parser, new[]{ "Timestamp", "Instruments", "Price", "Size", "ExchangeName", "BidPriceBBO", "AskPriceBBO", "BidSizeBBO", "AskSizeBBO", "BidExchangeBBO", "AskExchangeBBO", "DaysHighestPrice", "DaysLowestPrice", "DaysOpeningPrice", "DaysTotalVolume", "ExchangeCode", "ConditionCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mktdatamessage.MarketDepthLevel), global::Mktdatamessage.MarketDepthLevel.Parser, new[]{ "Price", "Size", "ExchangeCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mktdatamessage.QuoteUpdate), global::Mktdatamessage.QuoteUpdate.Parser, new[]{ "Timestamp", "Instruments", "TopOfBook" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mktdatamessage.BookDepthMessage), global::Mktdatamessage.BookDepthMessage.Parser, new[]{ "Timestamp", "Instruments", "BidBookLevels", "AskBookLevels", "NumBidLevels", "NumAskLevels", "ConditionCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mktdatamessage.QuoteMessagesBatch), global::Mktdatamessage.QuoteMessagesBatch.Parser, new[]{ "NumberOfMessages", "QuoteMessages" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mktdatamessage.TradeMessagesBatch), global::Mktdatamessage.TradeMessagesBatch.Parser, new[]{ "NumberOfMessages", "TradeMessages" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mktdatamessage.DepthMessagesBatch), global::Mktdatamessage.DepthMessagesBatch.Parser, new[]{ "NumberOfMessages", "DepthMessages" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mktdatamessage.DebugInfo), global::Mktdatamessage.DebugInfo.Parser, new[]{ "MessageCreatedTimestamp", "MessageSentTimestamp", "MessageNumber", "Other" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Instrument : pb::IMessage<Instrument> {
    private static readonly pb::MessageParser<Instrument> _parser = new pb::MessageParser<Instrument>(() => new Instrument());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Instrument> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mktdatamessage.MktdataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Instrument() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Instrument(Instrument other) : this() {
      instrumentType_ = other.instrumentType_;
      underlyingSymbol_ = other.underlyingSymbol_;
      expirationDay_ = other.expirationDay_;
      expirationMonth_ = other.expirationMonth_;
      expirationYear_ = other.expirationYear_;
      strike_ = other.strike_;
      isCallOption_ = other.isCallOption_;
      idx_ = other.idx_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Instrument Clone() {
      return new Instrument(this);
    }

    /// <summary>Field number for the "InstrumentType" field.</summary>
    public const int InstrumentTypeFieldNumber = 1;
    private global::Mktdatamessage.Instrument.Types.InstrType instrumentType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Mktdatamessage.Instrument.Types.InstrType InstrumentType {
      get { return instrumentType_; }
      set {
        instrumentType_ = value;
      }
    }

    /// <summary>Field number for the "UnderlyingSymbol" field.</summary>
    public const int UnderlyingSymbolFieldNumber = 2;
    private string underlyingSymbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UnderlyingSymbol {
      get { return underlyingSymbol_; }
      set {
        underlyingSymbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ExpirationDay" field.</summary>
    public const int ExpirationDayFieldNumber = 3;
    private int expirationDay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ExpirationDay {
      get { return expirationDay_; }
      set {
        expirationDay_ = value;
      }
    }

    /// <summary>Field number for the "ExpirationMonth" field.</summary>
    public const int ExpirationMonthFieldNumber = 4;
    private int expirationMonth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ExpirationMonth {
      get { return expirationMonth_; }
      set {
        expirationMonth_ = value;
      }
    }

    /// <summary>Field number for the "ExpirationYear" field.</summary>
    public const int ExpirationYearFieldNumber = 5;
    private int expirationYear_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ExpirationYear {
      get { return expirationYear_; }
      set {
        expirationYear_ = value;
      }
    }

    /// <summary>Field number for the "Strike" field.</summary>
    public const int StrikeFieldNumber = 6;
    private float strike_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Strike {
      get { return strike_; }
      set {
        strike_ = value;
      }
    }

    /// <summary>Field number for the "IsCallOption" field.</summary>
    public const int IsCallOptionFieldNumber = 7;
    private bool isCallOption_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsCallOption {
      get { return isCallOption_; }
      set {
        isCallOption_ = value;
      }
    }

    /// <summary>Field number for the "idx" field.</summary>
    public const int IdxFieldNumber = 8;
    private uint idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Instrument);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Instrument other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InstrumentType != other.InstrumentType) return false;
      if (UnderlyingSymbol != other.UnderlyingSymbol) return false;
      if (ExpirationDay != other.ExpirationDay) return false;
      if (ExpirationMonth != other.ExpirationMonth) return false;
      if (ExpirationYear != other.ExpirationYear) return false;
      if (Strike != other.Strike) return false;
      if (IsCallOption != other.IsCallOption) return false;
      if (Idx != other.Idx) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (InstrumentType != 0) hash ^= InstrumentType.GetHashCode();
      if (UnderlyingSymbol.Length != 0) hash ^= UnderlyingSymbol.GetHashCode();
      if (ExpirationDay != 0) hash ^= ExpirationDay.GetHashCode();
      if (ExpirationMonth != 0) hash ^= ExpirationMonth.GetHashCode();
      if (ExpirationYear != 0) hash ^= ExpirationYear.GetHashCode();
      if (Strike != 0F) hash ^= Strike.GetHashCode();
      if (IsCallOption != false) hash ^= IsCallOption.GetHashCode();
      if (Idx != 0) hash ^= Idx.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (InstrumentType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) InstrumentType);
      }
      if (UnderlyingSymbol.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UnderlyingSymbol);
      }
      if (ExpirationDay != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ExpirationDay);
      }
      if (ExpirationMonth != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ExpirationMonth);
      }
      if (ExpirationYear != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ExpirationYear);
      }
      if (Strike != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Strike);
      }
      if (IsCallOption != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsCallOption);
      }
      if (Idx != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Idx);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (InstrumentType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) InstrumentType);
      }
      if (UnderlyingSymbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UnderlyingSymbol);
      }
      if (ExpirationDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExpirationDay);
      }
      if (ExpirationMonth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExpirationMonth);
      }
      if (ExpirationYear != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExpirationYear);
      }
      if (Strike != 0F) {
        size += 1 + 4;
      }
      if (IsCallOption != false) {
        size += 1 + 1;
      }
      if (Idx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Idx);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Instrument other) {
      if (other == null) {
        return;
      }
      if (other.InstrumentType != 0) {
        InstrumentType = other.InstrumentType;
      }
      if (other.UnderlyingSymbol.Length != 0) {
        UnderlyingSymbol = other.UnderlyingSymbol;
      }
      if (other.ExpirationDay != 0) {
        ExpirationDay = other.ExpirationDay;
      }
      if (other.ExpirationMonth != 0) {
        ExpirationMonth = other.ExpirationMonth;
      }
      if (other.ExpirationYear != 0) {
        ExpirationYear = other.ExpirationYear;
      }
      if (other.Strike != 0F) {
        Strike = other.Strike;
      }
      if (other.IsCallOption != false) {
        IsCallOption = other.IsCallOption;
      }
      if (other.Idx != 0) {
        Idx = other.Idx;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            instrumentType_ = (global::Mktdatamessage.Instrument.Types.InstrType) input.ReadEnum();
            break;
          }
          case 18: {
            UnderlyingSymbol = input.ReadString();
            break;
          }
          case 24: {
            ExpirationDay = input.ReadInt32();
            break;
          }
          case 32: {
            ExpirationMonth = input.ReadInt32();
            break;
          }
          case 40: {
            ExpirationYear = input.ReadInt32();
            break;
          }
          case 53: {
            Strike = input.ReadFloat();
            break;
          }
          case 56: {
            IsCallOption = input.ReadBool();
            break;
          }
          case 64: {
            Idx = input.ReadUInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Instrument message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum InstrType {
        [pbr::OriginalName("EQUITY")] Equity = 0,
        [pbr::OriginalName("OPTION")] Option = 1,
        [pbr::OriginalName("FUTURE")] Future = 2,
      }

    }
    #endregion

  }

  public sealed partial class TradeMessage : pb::IMessage<TradeMessage> {
    private static readonly pb::MessageParser<TradeMessage> _parser = new pb::MessageParser<TradeMessage>(() => new TradeMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TradeMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mktdatamessage.MktdataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TradeMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TradeMessage(TradeMessage other) : this() {
      timestamp_ = other.timestamp_;
      instruments_ = other.instruments_.Clone();
      price_ = other.price_;
      size_ = other.size_;
      exchangeName_ = other.exchangeName_;
      bidPriceBBO_ = other.bidPriceBBO_;
      askPriceBBO_ = other.askPriceBBO_;
      bidSizeBBO_ = other.bidSizeBBO_;
      askSizeBBO_ = other.askSizeBBO_;
      bidExchangeBBO_ = other.bidExchangeBBO_;
      askExchangeBBO_ = other.askExchangeBBO_;
      daysHighestPrice_ = other.daysHighestPrice_;
      daysLowestPrice_ = other.daysLowestPrice_;
      daysOpeningPrice_ = other.daysOpeningPrice_;
      daysTotalVolume_ = other.daysTotalVolume_;
      exchangeCode_ = other.exchangeCode_;
      conditionCode_ = other.conditionCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TradeMessage Clone() {
      return new TradeMessage(this);
    }

    /// <summary>Field number for the "Timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "Instruments" field.</summary>
    public const int InstrumentsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Mktdatamessage.Instrument> _repeated_instruments_codec
        = pb::FieldCodec.ForMessage(18, global::Mktdatamessage.Instrument.Parser);
    private readonly pbc::RepeatedField<global::Mktdatamessage.Instrument> instruments_ = new pbc::RepeatedField<global::Mktdatamessage.Instrument>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mktdatamessage.Instrument> Instruments {
      get { return instruments_; }
    }

    /// <summary>Field number for the "Price" field.</summary>
    public const int PriceFieldNumber = 3;
    private float price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "Size" field.</summary>
    public const int SizeFieldNumber = 4;
    private uint size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "ExchangeName" field.</summary>
    public const int ExchangeNameFieldNumber = 5;
    private string exchangeName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExchangeName {
      get { return exchangeName_; }
      set {
        exchangeName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BidPriceBBO" field.</summary>
    public const int BidPriceBBOFieldNumber = 6;
    private float bidPriceBBO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float BidPriceBBO {
      get { return bidPriceBBO_; }
      set {
        bidPriceBBO_ = value;
      }
    }

    /// <summary>Field number for the "AskPriceBBO" field.</summary>
    public const int AskPriceBBOFieldNumber = 7;
    private float askPriceBBO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float AskPriceBBO {
      get { return askPriceBBO_; }
      set {
        askPriceBBO_ = value;
      }
    }

    /// <summary>Field number for the "BidSizeBBO" field.</summary>
    public const int BidSizeBBOFieldNumber = 8;
    private uint bidSizeBBO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint BidSizeBBO {
      get { return bidSizeBBO_; }
      set {
        bidSizeBBO_ = value;
      }
    }

    /// <summary>Field number for the "AskSizeBBO" field.</summary>
    public const int AskSizeBBOFieldNumber = 9;
    private uint askSizeBBO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint AskSizeBBO {
      get { return askSizeBBO_; }
      set {
        askSizeBBO_ = value;
      }
    }

    /// <summary>Field number for the "BidExchangeBBO" field.</summary>
    public const int BidExchangeBBOFieldNumber = 10;
    private string bidExchangeBBO_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BidExchangeBBO {
      get { return bidExchangeBBO_; }
      set {
        bidExchangeBBO_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AskExchangeBBO" field.</summary>
    public const int AskExchangeBBOFieldNumber = 11;
    private string askExchangeBBO_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AskExchangeBBO {
      get { return askExchangeBBO_; }
      set {
        askExchangeBBO_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DaysHighestPrice" field.</summary>
    public const int DaysHighestPriceFieldNumber = 12;
    private float daysHighestPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float DaysHighestPrice {
      get { return daysHighestPrice_; }
      set {
        daysHighestPrice_ = value;
      }
    }

    /// <summary>Field number for the "DaysLowestPrice" field.</summary>
    public const int DaysLowestPriceFieldNumber = 13;
    private float daysLowestPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float DaysLowestPrice {
      get { return daysLowestPrice_; }
      set {
        daysLowestPrice_ = value;
      }
    }

    /// <summary>Field number for the "DaysOpeningPrice" field.</summary>
    public const int DaysOpeningPriceFieldNumber = 14;
    private float daysOpeningPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float DaysOpeningPrice {
      get { return daysOpeningPrice_; }
      set {
        daysOpeningPrice_ = value;
      }
    }

    /// <summary>Field number for the "DaysTotalVolume" field.</summary>
    public const int DaysTotalVolumeFieldNumber = 15;
    private uint daysTotalVolume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DaysTotalVolume {
      get { return daysTotalVolume_; }
      set {
        daysTotalVolume_ = value;
      }
    }

    /// <summary>Field number for the "ExchangeCode" field.</summary>
    public const int ExchangeCodeFieldNumber = 16;
    private uint exchangeCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ExchangeCode {
      get { return exchangeCode_; }
      set {
        exchangeCode_ = value;
      }
    }

    /// <summary>Field number for the "ConditionCode" field.</summary>
    public const int ConditionCodeFieldNumber = 17;
    private uint conditionCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ConditionCode {
      get { return conditionCode_; }
      set {
        conditionCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TradeMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TradeMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if(!instruments_.Equals(other.instruments_)) return false;
      if (Price != other.Price) return false;
      if (Size != other.Size) return false;
      if (ExchangeName != other.ExchangeName) return false;
      if (BidPriceBBO != other.BidPriceBBO) return false;
      if (AskPriceBBO != other.AskPriceBBO) return false;
      if (BidSizeBBO != other.BidSizeBBO) return false;
      if (AskSizeBBO != other.AskSizeBBO) return false;
      if (BidExchangeBBO != other.BidExchangeBBO) return false;
      if (AskExchangeBBO != other.AskExchangeBBO) return false;
      if (DaysHighestPrice != other.DaysHighestPrice) return false;
      if (DaysLowestPrice != other.DaysLowestPrice) return false;
      if (DaysOpeningPrice != other.DaysOpeningPrice) return false;
      if (DaysTotalVolume != other.DaysTotalVolume) return false;
      if (ExchangeCode != other.ExchangeCode) return false;
      if (ConditionCode != other.ConditionCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      hash ^= instruments_.GetHashCode();
      if (Price != 0F) hash ^= Price.GetHashCode();
      if (Size != 0) hash ^= Size.GetHashCode();
      if (ExchangeName.Length != 0) hash ^= ExchangeName.GetHashCode();
      if (BidPriceBBO != 0F) hash ^= BidPriceBBO.GetHashCode();
      if (AskPriceBBO != 0F) hash ^= AskPriceBBO.GetHashCode();
      if (BidSizeBBO != 0) hash ^= BidSizeBBO.GetHashCode();
      if (AskSizeBBO != 0) hash ^= AskSizeBBO.GetHashCode();
      if (BidExchangeBBO.Length != 0) hash ^= BidExchangeBBO.GetHashCode();
      if (AskExchangeBBO.Length != 0) hash ^= AskExchangeBBO.GetHashCode();
      if (DaysHighestPrice != 0F) hash ^= DaysHighestPrice.GetHashCode();
      if (DaysLowestPrice != 0F) hash ^= DaysLowestPrice.GetHashCode();
      if (DaysOpeningPrice != 0F) hash ^= DaysOpeningPrice.GetHashCode();
      if (DaysTotalVolume != 0) hash ^= DaysTotalVolume.GetHashCode();
      if (ExchangeCode != 0) hash ^= ExchangeCode.GetHashCode();
      if (ConditionCode != 0) hash ^= ConditionCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Timestamp);
      }
      instruments_.WriteTo(output, _repeated_instruments_codec);
      if (Price != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Price);
      }
      if (Size != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Size);
      }
      if (ExchangeName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ExchangeName);
      }
      if (BidPriceBBO != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(BidPriceBBO);
      }
      if (AskPriceBBO != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(AskPriceBBO);
      }
      if (BidSizeBBO != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(BidSizeBBO);
      }
      if (AskSizeBBO != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(AskSizeBBO);
      }
      if (BidExchangeBBO.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(BidExchangeBBO);
      }
      if (AskExchangeBBO.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(AskExchangeBBO);
      }
      if (DaysHighestPrice != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(DaysHighestPrice);
      }
      if (DaysLowestPrice != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(DaysLowestPrice);
      }
      if (DaysOpeningPrice != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(DaysOpeningPrice);
      }
      if (DaysTotalVolume != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(DaysTotalVolume);
      }
      if (ExchangeCode != 0) {
        output.WriteRawTag(128, 1);
        output.WriteUInt32(ExchangeCode);
      }
      if (ConditionCode != 0) {
        output.WriteRawTag(136, 1);
        output.WriteUInt32(ConditionCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      size += instruments_.CalculateSize(_repeated_instruments_codec);
      if (Price != 0F) {
        size += 1 + 4;
      }
      if (Size != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Size);
      }
      if (ExchangeName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExchangeName);
      }
      if (BidPriceBBO != 0F) {
        size += 1 + 4;
      }
      if (AskPriceBBO != 0F) {
        size += 1 + 4;
      }
      if (BidSizeBBO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BidSizeBBO);
      }
      if (AskSizeBBO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AskSizeBBO);
      }
      if (BidExchangeBBO.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BidExchangeBBO);
      }
      if (AskExchangeBBO.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AskExchangeBBO);
      }
      if (DaysHighestPrice != 0F) {
        size += 1 + 4;
      }
      if (DaysLowestPrice != 0F) {
        size += 1 + 4;
      }
      if (DaysOpeningPrice != 0F) {
        size += 1 + 4;
      }
      if (DaysTotalVolume != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DaysTotalVolume);
      }
      if (ExchangeCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(ExchangeCode);
      }
      if (ConditionCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(ConditionCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TradeMessage other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      instruments_.Add(other.instruments_);
      if (other.Price != 0F) {
        Price = other.Price;
      }
      if (other.Size != 0) {
        Size = other.Size;
      }
      if (other.ExchangeName.Length != 0) {
        ExchangeName = other.ExchangeName;
      }
      if (other.BidPriceBBO != 0F) {
        BidPriceBBO = other.BidPriceBBO;
      }
      if (other.AskPriceBBO != 0F) {
        AskPriceBBO = other.AskPriceBBO;
      }
      if (other.BidSizeBBO != 0) {
        BidSizeBBO = other.BidSizeBBO;
      }
      if (other.AskSizeBBO != 0) {
        AskSizeBBO = other.AskSizeBBO;
      }
      if (other.BidExchangeBBO.Length != 0) {
        BidExchangeBBO = other.BidExchangeBBO;
      }
      if (other.AskExchangeBBO.Length != 0) {
        AskExchangeBBO = other.AskExchangeBBO;
      }
      if (other.DaysHighestPrice != 0F) {
        DaysHighestPrice = other.DaysHighestPrice;
      }
      if (other.DaysLowestPrice != 0F) {
        DaysLowestPrice = other.DaysLowestPrice;
      }
      if (other.DaysOpeningPrice != 0F) {
        DaysOpeningPrice = other.DaysOpeningPrice;
      }
      if (other.DaysTotalVolume != 0) {
        DaysTotalVolume = other.DaysTotalVolume;
      }
      if (other.ExchangeCode != 0) {
        ExchangeCode = other.ExchangeCode;
      }
      if (other.ConditionCode != 0) {
        ConditionCode = other.ConditionCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 18: {
            instruments_.AddEntriesFrom(input, _repeated_instruments_codec);
            break;
          }
          case 29: {
            Price = input.ReadFloat();
            break;
          }
          case 32: {
            Size = input.ReadUInt32();
            break;
          }
          case 42: {
            ExchangeName = input.ReadString();
            break;
          }
          case 53: {
            BidPriceBBO = input.ReadFloat();
            break;
          }
          case 61: {
            AskPriceBBO = input.ReadFloat();
            break;
          }
          case 64: {
            BidSizeBBO = input.ReadUInt32();
            break;
          }
          case 72: {
            AskSizeBBO = input.ReadUInt32();
            break;
          }
          case 82: {
            BidExchangeBBO = input.ReadString();
            break;
          }
          case 90: {
            AskExchangeBBO = input.ReadString();
            break;
          }
          case 101: {
            DaysHighestPrice = input.ReadFloat();
            break;
          }
          case 109: {
            DaysLowestPrice = input.ReadFloat();
            break;
          }
          case 117: {
            DaysOpeningPrice = input.ReadFloat();
            break;
          }
          case 120: {
            DaysTotalVolume = input.ReadUInt32();
            break;
          }
          case 128: {
            ExchangeCode = input.ReadUInt32();
            break;
          }
          case 136: {
            ConditionCode = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MarketDepthLevel : pb::IMessage<MarketDepthLevel> {
    private static readonly pb::MessageParser<MarketDepthLevel> _parser = new pb::MessageParser<MarketDepthLevel>(() => new MarketDepthLevel());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MarketDepthLevel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mktdatamessage.MktdataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MarketDepthLevel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MarketDepthLevel(MarketDepthLevel other) : this() {
      price_ = other.price_;
      size_ = other.size_;
      exchangeCode_ = other.exchangeCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MarketDepthLevel Clone() {
      return new MarketDepthLevel(this);
    }

    /// <summary>Field number for the "Price" field.</summary>
    public const int PriceFieldNumber = 1;
    private float price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "Size" field.</summary>
    public const int SizeFieldNumber = 2;
    private uint size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "ExchangeCode" field.</summary>
    public const int ExchangeCodeFieldNumber = 3;
    private uint exchangeCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ExchangeCode {
      get { return exchangeCode_; }
      set {
        exchangeCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MarketDepthLevel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MarketDepthLevel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Price != other.Price) return false;
      if (Size != other.Size) return false;
      if (ExchangeCode != other.ExchangeCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Price != 0F) hash ^= Price.GetHashCode();
      if (Size != 0) hash ^= Size.GetHashCode();
      if (ExchangeCode != 0) hash ^= ExchangeCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Price != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(Price);
      }
      if (Size != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Size);
      }
      if (ExchangeCode != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ExchangeCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Price != 0F) {
        size += 1 + 4;
      }
      if (Size != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Size);
      }
      if (ExchangeCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ExchangeCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MarketDepthLevel other) {
      if (other == null) {
        return;
      }
      if (other.Price != 0F) {
        Price = other.Price;
      }
      if (other.Size != 0) {
        Size = other.Size;
      }
      if (other.ExchangeCode != 0) {
        ExchangeCode = other.ExchangeCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 13: {
            Price = input.ReadFloat();
            break;
          }
          case 16: {
            Size = input.ReadUInt32();
            break;
          }
          case 24: {
            ExchangeCode = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class QuoteUpdate : pb::IMessage<QuoteUpdate> {
    private static readonly pb::MessageParser<QuoteUpdate> _parser = new pb::MessageParser<QuoteUpdate>(() => new QuoteUpdate());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuoteUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mktdatamessage.MktdataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuoteUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuoteUpdate(QuoteUpdate other) : this() {
      timestamp_ = other.timestamp_;
      instruments_ = other.instruments_.Clone();
      TopOfBook = other.topOfBook_ != null ? other.TopOfBook.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuoteUpdate Clone() {
      return new QuoteUpdate(this);
    }

    /// <summary>Field number for the "Timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "Instruments" field.</summary>
    public const int InstrumentsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Mktdatamessage.Instrument> _repeated_instruments_codec
        = pb::FieldCodec.ForMessage(18, global::Mktdatamessage.Instrument.Parser);
    private readonly pbc::RepeatedField<global::Mktdatamessage.Instrument> instruments_ = new pbc::RepeatedField<global::Mktdatamessage.Instrument>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mktdatamessage.Instrument> Instruments {
      get { return instruments_; }
    }

    /// <summary>Field number for the "TopOfBook" field.</summary>
    public const int TopOfBookFieldNumber = 3;
    private global::Mktdatamessage.MarketDepthLevel topOfBook_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Mktdatamessage.MarketDepthLevel TopOfBook {
      get { return topOfBook_; }
      set {
        topOfBook_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuoteUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuoteUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if(!instruments_.Equals(other.instruments_)) return false;
      if (!object.Equals(TopOfBook, other.TopOfBook)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      hash ^= instruments_.GetHashCode();
      if (topOfBook_ != null) hash ^= TopOfBook.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Timestamp);
      }
      instruments_.WriteTo(output, _repeated_instruments_codec);
      if (topOfBook_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TopOfBook);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      size += instruments_.CalculateSize(_repeated_instruments_codec);
      if (topOfBook_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TopOfBook);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuoteUpdate other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      instruments_.Add(other.instruments_);
      if (other.topOfBook_ != null) {
        if (topOfBook_ == null) {
          topOfBook_ = new global::Mktdatamessage.MarketDepthLevel();
        }
        TopOfBook.MergeFrom(other.TopOfBook);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 18: {
            instruments_.AddEntriesFrom(input, _repeated_instruments_codec);
            break;
          }
          case 26: {
            if (topOfBook_ == null) {
              topOfBook_ = new global::Mktdatamessage.MarketDepthLevel();
            }
            input.ReadMessage(topOfBook_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class BookDepthMessage : pb::IMessage<BookDepthMessage> {
    private static readonly pb::MessageParser<BookDepthMessage> _parser = new pb::MessageParser<BookDepthMessage>(() => new BookDepthMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BookDepthMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mktdatamessage.MktdataReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BookDepthMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BookDepthMessage(BookDepthMessage other) : this() {
      timestamp_ = other.timestamp_;
      instruments_ = other.instruments_.Clone();
      bidBookLevels_ = other.bidBookLevels_.Clone();
      askBookLevels_ = other.askBookLevels_.Clone();
      numBidLevels_ = other.numBidLevels_;
      numAskLevels_ = other.numAskLevels_;
      conditionCode_ = other.conditionCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BookDepthMessage Clone() {
      return new BookDepthMessage(this);
    }

    /// <summary>Field number for the "Timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "Instruments" field.</summary>
    public const int InstrumentsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Mktdatamessage.Instrument> _repeated_instruments_codec
        = pb::FieldCodec.ForMessage(18, global::Mktdatamessage.Instrument.Parser);
    private readonly pbc::RepeatedField<global::Mktdatamessage.Instrument> instruments_ = new pbc::RepeatedField<global::Mktdatamessage.Instrument>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mktdatamessage.Instrument> Instruments {
      get { return instruments_; }
    }

    /// <summary>Field number for the "BidBookLevels" field.</summary>
    public const int BidBookLevelsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Mktdatamessage.MarketDepthLevel> _repeated_bidBookLevels_codec
        = pb::FieldCodec.ForMessage(26, global::Mktdatamessage.MarketDepthLevel.Parser);
    private readonly pbc::RepeatedField<global::Mktdatamessage.MarketDepthLevel> bidBookLevels_ = new pbc::RepeatedField<global::Mktdatamessage.MarketDepthLevel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mktdatamessage.MarketDepthLevel> BidBookLevels {
      get { return bidBookLevels_; }
    }

    /// <summary>Field number for the "AskBookLevels" field.</summary>
    public const int AskBookLevelsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Mktdatamessage.MarketDepthLevel> _repeated_askBookLevels_codec
        = pb::FieldCodec.ForMessage(34, global::Mktdatamessage.MarketDepthLevel.Parser);
    private readonly pbc::RepeatedField<global::Mktdatamessage.MarketDepthLevel> askBookLevels_ = new pbc::RepeatedField<global::Mktdatamessage.MarketDepthLevel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mktdatamessage.MarketDepthLevel> AskBookLevels {
      get { return askBookLevels_; }
    }

    /// <summary>Field number for the "NumBidLevels" field.</summary>
    public const int NumBidLevelsFieldNumber = 5;
    private uint numBidLevels_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint NumBidLevels {
      get { return numBidLevels_; }
      set {
        numBidLevels_ = value;
      }
    }

    /// <summary>Field number for the "NumAskLevels" field.</summary>
    public const int NumAskLevelsFieldNumber = 6;
    private uint numAskLevels_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint NumAskLevels {
      get { return numAskLevels_; }
      set {
        numAskLevels_ = value;
      }
    }

    /// <summary>Field number for the "ConditionCode" field.</summary>
    public const int ConditionCodeFieldNumber = 7;
    private uint conditionCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ConditionCode {
      get { return conditionCode_; }
      set {
        conditionCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BookDepthMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BookDepthMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if(!instruments_.Equals(other.instruments_)) return false;
      if(!bidBookLevels_.Equals(other.bidBookLevels_)) return false;
      if(!askBookLevels_.Equals(other.askBookLevels_)) return false;
      if (NumBidLevels != other.NumBidLevels) return false;
      if (NumAskLevels != other.NumAskLevels) return false;
      if (ConditionCode != other.ConditionCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      hash ^= instruments_.GetHashCode();
      hash ^= bidBookLevels_.GetHashCode();
      hash ^= askBookLevels_.GetHashCode();
      if (NumBidLevels != 0) hash ^= NumBidLevels.GetHashCode();
      if (NumAskLevels != 0) hash ^= NumAskLevels.GetHashCode();
      if (ConditionCode != 0) hash ^= ConditionCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Timestamp);
      }
      instruments_.WriteTo(output, _repeated_instruments_codec);
      bidBookLevels_.WriteTo(output, _repeated_bidBookLevels_codec);
      askBookLevels_.WriteTo(output, _repeated_askBookLevels_codec);
      if (NumBidLevels != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(NumBidLevels);
      }
      if (NumAskLevels != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(NumAskLevels);
      }
      if (ConditionCode != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(ConditionCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      size += instruments_.CalculateSize(_repeated_instruments_codec);
      size += bidBookLevels_.CalculateSize(_repeated_bidBookLevels_codec);
      size += askBookLevels_.CalculateSize(_repeated_askBookLevels_codec);
      if (NumBidLevels != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumBidLevels);
      }
      if (NumAskLevels != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumAskLevels);
      }
      if (ConditionCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ConditionCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BookDepthMessage other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      instruments_.Add(other.instruments_);
      bidBookLevels_.Add(other.bidBookLevels_);
      askBookLevels_.Add(other.askBookLevels_);
      if (other.NumBidLevels != 0) {
        NumBidLevels = other.NumBidLevels;
      }
      if (other.NumAskLevels != 0) {
        NumAskLevels = other.NumAskLevels;
      }
      if (other.ConditionCode != 0) {
        ConditionCode = other.ConditionCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 18: {
            instruments_.AddEntriesFrom(input, _repeated_instruments_codec);
            break;
          }
          case 26: {
            bidBookLevels_.AddEntriesFrom(input, _repeated_bidBookLevels_codec);
            break;
          }
          case 34: {
            askBookLevels_.AddEntriesFrom(input, _repeated_askBookLevels_codec);
            break;
          }
          case 40: {
            NumBidLevels = input.ReadUInt32();
            break;
          }
          case 48: {
            NumAskLevels = input.ReadUInt32();
            break;
          }
          case 56: {
            ConditionCode = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class QuoteMessagesBatch : pb::IMessage<QuoteMessagesBatch> {
    private static readonly pb::MessageParser<QuoteMessagesBatch> _parser = new pb::MessageParser<QuoteMessagesBatch>(() => new QuoteMessagesBatch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuoteMessagesBatch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mktdatamessage.MktdataReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuoteMessagesBatch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuoteMessagesBatch(QuoteMessagesBatch other) : this() {
      numberOfMessages_ = other.numberOfMessages_;
      quoteMessages_ = other.quoteMessages_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuoteMessagesBatch Clone() {
      return new QuoteMessagesBatch(this);
    }

    /// <summary>Field number for the "NumberOfMessages" field.</summary>
    public const int NumberOfMessagesFieldNumber = 1;
    private uint numberOfMessages_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint NumberOfMessages {
      get { return numberOfMessages_; }
      set {
        numberOfMessages_ = value;
      }
    }

    /// <summary>Field number for the "QuoteMessages" field.</summary>
    public const int QuoteMessagesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Mktdatamessage.QuoteUpdate> _repeated_quoteMessages_codec
        = pb::FieldCodec.ForMessage(18, global::Mktdatamessage.QuoteUpdate.Parser);
    private readonly pbc::RepeatedField<global::Mktdatamessage.QuoteUpdate> quoteMessages_ = new pbc::RepeatedField<global::Mktdatamessage.QuoteUpdate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mktdatamessage.QuoteUpdate> QuoteMessages {
      get { return quoteMessages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuoteMessagesBatch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuoteMessagesBatch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumberOfMessages != other.NumberOfMessages) return false;
      if(!quoteMessages_.Equals(other.quoteMessages_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NumberOfMessages != 0) hash ^= NumberOfMessages.GetHashCode();
      hash ^= quoteMessages_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NumberOfMessages != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(NumberOfMessages);
      }
      quoteMessages_.WriteTo(output, _repeated_quoteMessages_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NumberOfMessages != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumberOfMessages);
      }
      size += quoteMessages_.CalculateSize(_repeated_quoteMessages_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuoteMessagesBatch other) {
      if (other == null) {
        return;
      }
      if (other.NumberOfMessages != 0) {
        NumberOfMessages = other.NumberOfMessages;
      }
      quoteMessages_.Add(other.quoteMessages_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            NumberOfMessages = input.ReadUInt32();
            break;
          }
          case 18: {
            quoteMessages_.AddEntriesFrom(input, _repeated_quoteMessages_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class TradeMessagesBatch : pb::IMessage<TradeMessagesBatch> {
    private static readonly pb::MessageParser<TradeMessagesBatch> _parser = new pb::MessageParser<TradeMessagesBatch>(() => new TradeMessagesBatch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TradeMessagesBatch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mktdatamessage.MktdataReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TradeMessagesBatch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TradeMessagesBatch(TradeMessagesBatch other) : this() {
      numberOfMessages_ = other.numberOfMessages_;
      tradeMessages_ = other.tradeMessages_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TradeMessagesBatch Clone() {
      return new TradeMessagesBatch(this);
    }

    /// <summary>Field number for the "NumberOfMessages" field.</summary>
    public const int NumberOfMessagesFieldNumber = 1;
    private uint numberOfMessages_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint NumberOfMessages {
      get { return numberOfMessages_; }
      set {
        numberOfMessages_ = value;
      }
    }

    /// <summary>Field number for the "TradeMessages" field.</summary>
    public const int TradeMessagesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Mktdatamessage.TradeMessage> _repeated_tradeMessages_codec
        = pb::FieldCodec.ForMessage(18, global::Mktdatamessage.TradeMessage.Parser);
    private readonly pbc::RepeatedField<global::Mktdatamessage.TradeMessage> tradeMessages_ = new pbc::RepeatedField<global::Mktdatamessage.TradeMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mktdatamessage.TradeMessage> TradeMessages {
      get { return tradeMessages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TradeMessagesBatch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TradeMessagesBatch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumberOfMessages != other.NumberOfMessages) return false;
      if(!tradeMessages_.Equals(other.tradeMessages_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NumberOfMessages != 0) hash ^= NumberOfMessages.GetHashCode();
      hash ^= tradeMessages_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NumberOfMessages != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(NumberOfMessages);
      }
      tradeMessages_.WriteTo(output, _repeated_tradeMessages_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NumberOfMessages != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumberOfMessages);
      }
      size += tradeMessages_.CalculateSize(_repeated_tradeMessages_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TradeMessagesBatch other) {
      if (other == null) {
        return;
      }
      if (other.NumberOfMessages != 0) {
        NumberOfMessages = other.NumberOfMessages;
      }
      tradeMessages_.Add(other.tradeMessages_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            NumberOfMessages = input.ReadUInt32();
            break;
          }
          case 18: {
            tradeMessages_.AddEntriesFrom(input, _repeated_tradeMessages_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DepthMessagesBatch : pb::IMessage<DepthMessagesBatch> {
    private static readonly pb::MessageParser<DepthMessagesBatch> _parser = new pb::MessageParser<DepthMessagesBatch>(() => new DepthMessagesBatch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DepthMessagesBatch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mktdatamessage.MktdataReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DepthMessagesBatch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DepthMessagesBatch(DepthMessagesBatch other) : this() {
      numberOfMessages_ = other.numberOfMessages_;
      depthMessages_ = other.depthMessages_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DepthMessagesBatch Clone() {
      return new DepthMessagesBatch(this);
    }

    /// <summary>Field number for the "NumberOfMessages" field.</summary>
    public const int NumberOfMessagesFieldNumber = 1;
    private uint numberOfMessages_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint NumberOfMessages {
      get { return numberOfMessages_; }
      set {
        numberOfMessages_ = value;
      }
    }

    /// <summary>Field number for the "DepthMessages" field.</summary>
    public const int DepthMessagesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Mktdatamessage.BookDepthMessage> _repeated_depthMessages_codec
        = pb::FieldCodec.ForMessage(18, global::Mktdatamessage.BookDepthMessage.Parser);
    private readonly pbc::RepeatedField<global::Mktdatamessage.BookDepthMessage> depthMessages_ = new pbc::RepeatedField<global::Mktdatamessage.BookDepthMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mktdatamessage.BookDepthMessage> DepthMessages {
      get { return depthMessages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DepthMessagesBatch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DepthMessagesBatch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumberOfMessages != other.NumberOfMessages) return false;
      if(!depthMessages_.Equals(other.depthMessages_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NumberOfMessages != 0) hash ^= NumberOfMessages.GetHashCode();
      hash ^= depthMessages_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NumberOfMessages != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(NumberOfMessages);
      }
      depthMessages_.WriteTo(output, _repeated_depthMessages_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NumberOfMessages != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumberOfMessages);
      }
      size += depthMessages_.CalculateSize(_repeated_depthMessages_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DepthMessagesBatch other) {
      if (other == null) {
        return;
      }
      if (other.NumberOfMessages != 0) {
        NumberOfMessages = other.NumberOfMessages;
      }
      depthMessages_.Add(other.depthMessages_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            NumberOfMessages = input.ReadUInt32();
            break;
          }
          case 18: {
            depthMessages_.AddEntriesFrom(input, _repeated_depthMessages_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DebugInfo : pb::IMessage<DebugInfo> {
    private static readonly pb::MessageParser<DebugInfo> _parser = new pb::MessageParser<DebugInfo>(() => new DebugInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DebugInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mktdatamessage.MktdataReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DebugInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DebugInfo(DebugInfo other) : this() {
      messageCreatedTimestamp_ = other.messageCreatedTimestamp_;
      messageSentTimestamp_ = other.messageSentTimestamp_;
      messageNumber_ = other.messageNumber_;
      other_ = other.other_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DebugInfo Clone() {
      return new DebugInfo(this);
    }

    /// <summary>Field number for the "MessageCreatedTimestamp" field.</summary>
    public const int MessageCreatedTimestampFieldNumber = 1;
    private ulong messageCreatedTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong MessageCreatedTimestamp {
      get { return messageCreatedTimestamp_; }
      set {
        messageCreatedTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "MessageSentTimestamp" field.</summary>
    public const int MessageSentTimestampFieldNumber = 2;
    private ulong messageSentTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong MessageSentTimestamp {
      get { return messageSentTimestamp_; }
      set {
        messageSentTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "MessageNumber" field.</summary>
    public const int MessageNumberFieldNumber = 3;
    private ulong messageNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong MessageNumber {
      get { return messageNumber_; }
      set {
        messageNumber_ = value;
      }
    }

    /// <summary>Field number for the "Other" field.</summary>
    public const int OtherFieldNumber = 4;
    private string other_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Other {
      get { return other_; }
      set {
        other_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DebugInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DebugInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageCreatedTimestamp != other.MessageCreatedTimestamp) return false;
      if (MessageSentTimestamp != other.MessageSentTimestamp) return false;
      if (MessageNumber != other.MessageNumber) return false;
      if (Other != other.Other) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageCreatedTimestamp != 0UL) hash ^= MessageCreatedTimestamp.GetHashCode();
      if (MessageSentTimestamp != 0UL) hash ^= MessageSentTimestamp.GetHashCode();
      if (MessageNumber != 0UL) hash ^= MessageNumber.GetHashCode();
      if (Other.Length != 0) hash ^= Other.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MessageCreatedTimestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(MessageCreatedTimestamp);
      }
      if (MessageSentTimestamp != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(MessageSentTimestamp);
      }
      if (MessageNumber != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(MessageNumber);
      }
      if (Other.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Other);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MessageCreatedTimestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MessageCreatedTimestamp);
      }
      if (MessageSentTimestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MessageSentTimestamp);
      }
      if (MessageNumber != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MessageNumber);
      }
      if (Other.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Other);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DebugInfo other) {
      if (other == null) {
        return;
      }
      if (other.MessageCreatedTimestamp != 0UL) {
        MessageCreatedTimestamp = other.MessageCreatedTimestamp;
      }
      if (other.MessageSentTimestamp != 0UL) {
        MessageSentTimestamp = other.MessageSentTimestamp;
      }
      if (other.MessageNumber != 0UL) {
        MessageNumber = other.MessageNumber;
      }
      if (other.Other.Length != 0) {
        Other = other.Other;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MessageCreatedTimestamp = input.ReadUInt64();
            break;
          }
          case 16: {
            MessageSentTimestamp = input.ReadUInt64();
            break;
          }
          case 24: {
            MessageNumber = input.ReadUInt64();
            break;
          }
          case 34: {
            Other = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
